# Generated by Django 2.0 on 2018-01-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributes',
            old_name='Attribute_Code',
            new_name='Attribute_Label',
        ),
    ]
