# Generated by Django 2.0 on 2018-01-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_auto_20180112_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='Standard_variable',
            field=models.CharField(default='default_var', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='options',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='_options_connections_+', to='attributes.Options'),
        ),
        migrations.AddField(
            model_name='options',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
