# Generated by Django 2.0 on 2018-01-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_auto_20180112_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='Standard_variable',
        ),
        migrations.AddField(
            model_name='attributes',
            name='Standard_variable',
            field=models.CharField(default='default_var', max_length=30),
            preserve_default=False,
        ),
    ]
