# Generated by Django 2.0 on 2018-01-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_auto_20180112_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='Standard_variable',
        ),
        migrations.AddField(
            model_name='attributes',
            name='Standard_variable_attr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='Standard_variable_option',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
