# Generated by Django 2.0 on 2018-01-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0005_auto_20180112_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attribute', models.IntegerField()),
                ('Attribute_Label', models.CharField(max_length=200)),
                ('Standard_variable_attr', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option_Code', models.IntegerField()),
                ('Option_Label', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
                ('Standard_variable_option', models.CharField(blank=True, max_length=30, null=True)),
                ('Attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute')),
                ('connections', models.ManyToManyField(blank=True, related_name='_option_connections_+', to='attributes.Option')),
            ],
        ),
        migrations.RemoveField(
            model_name='options',
            name='Attribute',
        ),
        migrations.RemoveField(
            model_name='options',
            name='connections',
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
