# Generated by Django 2.0.1 on 2018-01-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_auto_20180112_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='Standard_question_wording_attr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='Standard_question_wording_option',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
